#! /bin/bash

# nginx log format
# log_format combined '$remote_addr - $remote_user [$time_local] '
#                   '"$request" $status $body_bytes_sent '
#                   '"$http_referer" "$http_user_agent"';

echo "Top 5 IP addresses with the most requests:"

grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' nginx-access.log \
  | sort | uniq -c | sort -nr | head -5 \
  | awk '{print $2, "-", $1, "requests"}'



echo "Top 5 most requested paths:"

awk '{print $7}' nginx-access.log \
  | sort \
  | uniq -c \
  | sort -nr \
  | head -5 \
  | awk '{print $2, "-", $1, "requests"}'

echo "Top 5 response status codes:"

awk '{print $9}' nginx-access.log \
  | sort \
  | uniq -c \
  | sort -nr \
  | head -5 \
  | awk '{print $2, "-", $1, "requests"}'

